### PR TITLE
feat(routes): split up into different files

### PR DESCRIPTION
**Pull request by heybereket**
refactor pr:
- split all routes into individual files

### CODE REVIEW

**Review by cursorsdottsx — APPROVED** [review]
maybe if there was a way to get rid of all the repetitive `const router = Router()` lines it would be perfect, but so far it looks good

**Comment by cursorsdottsx** [comment]
progress update please

**Comment by cursorsdottsx** [comment]
make sure to use [`loadRoutes`](https://github.com/oasis-sh/api/pull/11) if you can (i will add it if you are unable to do so)

pull new changes, no conflicts

**Comment by heybereket** [comment]
> make sure to use [`loadRoutes`](https://github.com/oasis-sh/api/pull/11) if you can (i will add it if you are unable to do so)
> 
> pull new changes, no conflicts

making prs separately - this will just be to merge the final splitted routes to the dev/master branch  👍🏽

**Pull request merged**
